name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
   runs-on: ubuntu-latest

   steps:
    - uses: actions/checkout@v2

    - name: Build
      run: npm install && npm run build

    - name: Deploy
      uses: cross-the-world/scp-pipeline@master
      env:
        WELCOME: "ssh scp ssh pipelines"
        LASTSSH: "Doing something after copying"
      with:
        host: ${{ secrets.W_HOST }}
        user: ${{ secrets.W_USER }}
        pass: ${{ secrets.W_PASS }}
        connect_timeout: 10s
        local: './dist/*'
        remote: /home/webserver/static/jenkins/cicd
